version: "3.0"
services:
    app:
        build: "."
        volumes:
            - .env:/app/.env
        restart: always
    
    portainer:
        image: portainer/portainer-ce
        volumes:
            - portainer_data:/data
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
        ports:
            - 8000:8000
            - 9000:9000
        restart: always

volumes:
    portainer_data: