on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on:
      - self-hosted
      - raspi

    steps:
      - uses: actions/checkout@v2
      - run: |
          workDir="$HOME/production/k2-discord-bot"
          rsync \
            --exclude=.git \
            --exclude=.env \
            --delete \
            --recursive \
            ./ "$workDir"
          cd "$workDir"
          docker-compose build
          docker-compose up -d